# pavlovia_cleaner || v2023.10.14

pavlovia_cleaner <- function(file) {

  # ----- Packages -----
  
  ## Loading packages
  if (require("pacman") == FALSE){
    install.packages("pacman")
  }
  
  ## Loading in my packages with my pacman manager
  pacman::p_load(assertthat, here, jsonlite, tidyverse)
  
  # ----- QA Checks ----- 

  if (!is.string(file)){
    stop(paste("file refers to the raw file generated by Pavlovia in .csv format. It must be valid string, but your entry (",
               file, ") is not a string. Please enter a string and try again."))
  }
  
  if (!str_detect(file, "\\.csv")){
    stop(paste("file refers to the raw file generated by Pavlovia in .csv format. It must be valid .csv file, but your entry does not include a .csv file name (",
               file, "). Please enter a file name with a valid .csv extension and try again."))
  }
  
  if (!file.exists(file)){
    stop(paste("file refers to the raw file generated by Pavlovia in .csv format. It must be valid filepath, but no file exists at your entry (",
               file, "). Please enter a valid file path and try again."))
  }
  
  # ----- Setup -----
  
  ## Creating a general dataframe
  df <- read.csv(file,
              na.strings = c(" ", ""))
  
  ## If no tasks occurred ...
  if (all(names(df) != "task")){
    stop(paste("No usable data was found for datafile: ", file, ". Processing of this file has been terminated."))
  }
  
  ## If no videos were shown ...
  if (all(df$task != "Stimulus")){
    stop(paste("No video trials were found for datafile: ", file, ". Processing of this file has been terminated."))
  }
  
  # ----- Cleaning Observation Data -----
  
  ## Creating a dataframe of trial by trial observations
  df_observ <- df %>%
            subset(select = c("task", "time_elapsed", "rt", 
                     "stimulus", "response", "choices"))
  
  ## Creating a new trial-level dataframe
  df_trials <- data.frame(Trial = 1:length(which(df_observ$task == "Stimulus")))
  
  ## If any videos were shown ...
  if (any(df_observ$task == "Stimulus")){
    
    ## Extracting Stimulus Information
    df_trials$Stimulus <- df_observ$stimulus[df_observ$task == "Stimulus" & !is.na(df_observ$task)] %>%
                          gsub('.*/(\\w+)\\.mp4.*', '\\1',
                               x = .)
  }
    
  ## Extracting Choice Information
  Choice_Order <- df_observ$choices[df_observ$task == "Strategy_Choice" & !is.na(df_observ$task)][1] %>%
                  gsub("\\\\", "", .) %>%
                  regmatches(., gregexpr('(?<=">)[^<]+', ., perl=TRUE)) %>%
                  unlist()
  
  df_trials$Choice <- df_observ$response[df_observ$task == "Strategy_Choice" & !is.na(df_observ$task)] %>%
                      as.numeric() %>%
                      sapply(., function(x) x + 1) %>%
                      Choice_Order[.]
  
  ## Extracting Choice Response Time
  df_trials$RT_sec_Choice <- as.numeric(df_observ$rt[df_observ$task == "Strategy_Choice" & !is.na(df_observ$task)])/1000
  
  ## Extracting Reported Intensity Before
  df_trials$IntBefore <- df_observ$response[df_observ$task == "Intensity_Baseline" & !is.na(df_observ$task)]
  
  ## Extracting Baseline Intensity Response Time
  df_trials$RT_sec_IntBefore <- as.numeric(df_observ$rt[df_observ$task == "Intensity_Baseline" & !is.na(df_observ$task)])/1000
  
  ## Extracting Reported Intensity After
  df_trials$IntAfter <- df_observ$response[df_observ$task == "Intensity_Video" & !is.na(df_observ$task)]
  
  ## Extracting Post Exposure Intensity Response Time
  df_trials$RT_sec_IntAfter <- as.numeric(df_observ$rt[df_observ$task == "Intensity_Video" & !is.na(df_observ$task)])/1000
  
  ## If no regulation strategy was chosen
  if (!all(df_trials$Choice == "Neither")){
    
    ## Extracting Reported Intensity Reduction
    df_trials$IntReduce[df_trials$Choice != "Neither"] <- df_observ$response[df_observ$task == "Intensity_Reduction" & !is.na(df_observ$task)]
    
    ## Extracting Intensity Reduction Response Time
    df_trials$RT_sec_IntReduce[df_trials$Choice != "Neither"] <- as.numeric(df_observ$rt[df_observ$task == "Intensity_Reduction" & !is.na(df_observ$task)])/1000
    
    ## Extracting Reported Effort
    df_trials$Effort[df_trials$Choice != "Neither"] <- df_observ$response[df_observ$task == "Effort" & !is.na(df_observ$task)] %>%
                                                       gsub("[^0-9.]", "", .) %>%
                                                       as.numeric()
    
    ## Extracting Effort Response Time
    df_trials$RT_sec_Effort[df_trials$Choice != "Neither"] <- as.numeric(df_observ$rt[df_observ$task == "Effort" & !is.na(df_observ$task)])/1000
    
    ## Extracting Reported Success
    df_trials$Success[df_trials$Choice != "Neither"] <- df_observ$response[df_observ$task == "Success" & !is.na(df_observ$task)] %>%
                                                        gsub("[^0-9.]", "", .) %>%
                                                        as.numeric()
    
    ## Extracting Success Response Time
    df_trials$RT_sec_Success[df_trials$Choice != "Neither"] <- as.numeric(df_observ$rt[df_observ$task == "Success" & !is.na(df_observ$task)])/1000
    
  }
  
  rm(df_observ, Choice_Order)
  
  # ----- Cleaning Scale Data ------
  
  if (any(df$task[!is.na(df$task)] == "Scale")){
    
    ## Creating a dataframe of scale responses
    df_scale <- df[df$task == "Scale" & !is.na(df$task),] %>%
      subset(select = c("trial_index", "time_elapsed", "rt", "response", "question_order"))
    
    ## Extracting ERQ Column Names
    ERQ_cols <- strsplit(df_scale$response[grepl("ERQ", df_scale$response)], ",") %>%
      unlist() %>%
      gsub('.*"(ERQ_\\d+)".*', '\\1', .)
    
    ## Extracting ERQ Values
    ERQ_vals <- strsplit(df_scale$response[grepl("ERQ", df_scale$response)], ",") %>%
      unlist() %>%
      gsub('.*:(\\d+).*', '\\1', .)
    
    ## Extracting IUS Column Names
    IUS_cols <- strsplit(df_scale$response[grepl("IUS", df_scale$response)], ",") %>%
      unlist() %>%
      gsub('.*"(IUS-SF_\\d+)".*', '\\1', .)
    
    ## Extracting IUS Values
    IUS_vals <- strsplit(df_scale$response[grepl("IUS", df_scale$response)], ",") %>%
      unlist() %>%
      gsub('.*:(\\d+).*', '\\1', .)
    
    ## Extracting DERS Column Names
    DERS_cols <- strsplit(df_scale$response[grepl("DERS", df_scale$response)], ",") %>%
      unlist() %>%
      gsub('.*"(DERS_\\d+)".*', '\\1', .)
    
    ## Extracting DERS Values
    DERS_vals <- strsplit(df_scale$response[grepl("DERS", df_scale$response)], ",") %>%
      unlist() %>%
      gsub('.*:(\\d+).*', '\\1', .)
    
    ## Creating arrays of Questions and Values
    Scale_Question <- c(ERQ_cols, DERS_cols, IUS_cols)
    Scale_Value <- c(ERQ_vals, DERS_vals, IUS_vals)
    
    ## Capturing how long scales took to complete
    Scale_RT_sec <- as.numeric(df_scale$rt)/1000
    Scale_RT_sec <- c(rep(Scale_RT_sec[1], length(ERQ_cols)),
                      rep(Scale_RT_sec[2], length(DERS_cols)),
                      rep(Scale_RT_sec[3], length(IUS_cols)))
    
    ## Creating a dataframe
    df_scale <- data.frame(Scale_Question,
                           Scale_Value,
                           Scale_RT_sec)
    
    ## Cleaning our space
    rm(ERQ_cols, DERS_cols, IUS_cols, ERQ_vals, DERS_vals, IUS_vals, Scale_Question, Scale_Value, Scale_RT_sec)
    
    ## Calculating ERQ Summary Scores
    ## Calculating the suppression subscale
    df_trials$ERQ_Supp <- which(df_scale$Scale_Question %in% c("ERQ_02", "ERQ_04", "ERQ_06", "ERQ_09")) %>%
      df_scale$Scale_Value[.] %>%
      as.numeric() %>%
      sum()
    
    ## Calculating the reappraisal subscale
    df_trials$ERQ_Reapp <- which(df_scale$Scale_Question %in% c("ERQ_01", "ERQ_03", "ERQ_05", "ERQ_07", "ERQ_08", "ERQ_10")) %>%
      df_scale$Scale_Value[.] %>%
      as.numeric() %>%
      sum()
    
    df_trials$RT_sec_ERQ <- df_scale$Scale_RT_sec[df_scale$Scale_Question == "ERQ_01"]
    
    ## Calculating DERS Summary Scores
    ## Reverse Scoring Specific Cases
    for (VALUE in c("DERS_01", "DERS_02", "DERS_06", "DERS_07", 
                    "DERS_08", "DERS_10", "DERS_17", "DERS_20", 
                    "DERS_22", "DERS_24", "DERS_34")){
      df_scale$Scale_Value[df_scale$Scale_Question == VALUE] <- 6 - as.numeric(df_scale$Scale_Value[df_scale$Scale_Question == VALUE])
    }
    
    df_trials$DERS <- grepl("^DERS_", df_scale$Scale_Question) %>%
      df_scale$Scale_Value[.] %>%
      as.numeric() %>%
      sum()
    
    df_trials$DERS_Nonaccept <- which(df_scale$Scale_Question %in% c("DERS_11", "DERS_12", "DERS_21", "DERS_23", "DERS_25", "DERS_29")) %>%
      df_scale$Scale_Value[.] %>%
      as.numeric() %>%
      sum()
    
    df_trials$DERS_Goals <-  which(df_scale$Scale_Question %in% c("DERS_13", "DERS_18", "DERS_20", "DERS_26", "DERS_33"))%>%
      df_scale$Scale_Value[.] %>%
      as.numeric() %>%
      sum()
    
    df_trials$DERS_Impulse <-  which(df_scale$Scale_Question %in% c("DERS_03", "DERS_14", "DERS_19", "DERS_24", "DERS_27", "DERS_32"))%>%
      df_scale$Scale_Value[.] %>%
      as.numeric() %>%
      sum()
    
    df_trials$DERS_Awareness <- which(df_scale$Scale_Question %in% c("DERS_02", "DERS_06", "DERS_08", "DERS_10", "DERS_17", "DERS_34")) %>%
      df_scale$Scale_Value[.] %>%
      as.numeric() %>%
      sum()
    
    df_trials$DERS_Strategies <- which(df_scale$Scale_Question %in% c("DERS_15", "DERS_16", "DERS_22", "DERS_28", "DERS_30", "DERS_31", "DERS_35", "DERS_36")) %>%
      df_scale$Scale_Value[.] %>%
      as.numeric() %>%
      sum()
    
    df_trials$DERS_Clarity <- which(df_scale$Scale_Question %in% c("DERS_01", "DERS_04", "DERS_05", "DERS_07", "DERS_09")) %>%
      df_scale$Scale_Value[.] %>%
      as.numeric() %>%
      sum()
    
    ## Calculating Time to complete
    df_trials$RT_sec_DERS <- df_scale$Scale_RT_sec[df_scale$Scale_Question == "DERS_01"]
    
    ## Calculating IUS Summary Scores
    df_trials$IUS <- grepl("^IUS-SF_", df_scale$Scale_Question) %>%
      df_scale$Scale_Value[.] %>%
      as.numeric() %>%
      sum()
    
    ## Calculating the subscales
    df_trials$IUS_F1 <- which(df_scale$Scale_Question %in% c("IUS-SF_01", "IUS-SF_02", "IUS-SF_04", "IUS-SF_05", "IUS-SF_08", "IUS-SF_09", "IUS-SF_11")) %>%
      df_scale$Scale_Value[.] %>%
      as.numeric() %>%
      sum()
    
    df_trials$IUS_F2 <- which(df_scale$Scale_Question %in% c("IUS-SF_03", "IUS-SF_06", "IUS-SF_07", "IUS-SF_10", "IUS-SF_12")) %>%
      df_scale$Scale_Value[.] %>%
      as.numeric() %>%
      sum()
    
    ## Calculating Time to complete
    df_trials$RT_sec_IUS <- df_scale$Scale_RT_sec[df_scale$Scale_Question == "IUS-SF_01"]
    
    ## Checking if we have demographics information
    if (any(df$task == "Demographics" & !is.na(df$task))){
     
      ## Working on Demographics
      df_demo <- df$response[df$task == "Demographics" & !is.na(df$task)] %>%
                    fromJSON() %>%
                    as.data.frame()
      
      ## If the one of the demographics has multiple entries
      if (nrow(df_demo) > 1) {
        
        ## We'll iterate throuhg each column
        for (COL in 1:ncol(df_demo)){
          
          ## and find all cases where we have multiple different values
          if (!all(df_demo[,COL] == df_demo[1,COL])){
            
            ## Then we'll copy all of those valuse to our first row
            df_demo[1,COL] <- paste(df_demo[,COL],sep = " / ", collapse = " ")
          }
        }
      }
      
      ## and merge it with the preexisting dataframe
      df_trials <- df_demo[1,] %>%
                   cbind(df_trials, .)
      
    }
    
    ## Cleaning our space
    rm(df_scale, VALUE, df_demo)
  }
  
  # ----- Cleaning Session Data -----
  
  ## Creating a dataframe of variables that should be consistent across the session
  df_session_orig <- df %>%
                subset(select = c("subject_id","success", "time",  "timeout", "failed_images", "failed_audio", 
                                  "failed_video", "width", "height", "webaudio", "browser",
                                  "browser_version", "mobile", "os", "fullscreen", "vsync_rate", "condition")) %>%
                .[rowSums(is.na(.)) != ncol(.), ]
  
  cols_session <- c("PID", "Date", "Start_Time", "End_Time", "Condition", "Failures", "ScreenWidth", "ScreenHeight", "WebAudio",
                    "Browser", "Browser_Version", "MobileUsed", "OS", "FullScreenUsed",
                    "VSync_Rate_Avg", "VSync_Rate_SD", "Horror_Enjoy", "Familiarity", "Familiar_specific",
                    "Attention_Check", "Difficulties", "Questions")
  
  df_session <- as.data.frame(matrix(data = NA, 
                                     nrow = 1,
                                     ncol = length(cols_session),
                                     dimnames = list(1,
                                                     cols_session)))
  
  ## Extracting PID
  df_session$PID <- df$subject_id[1] %>%
                    gsub("[^[:alnum:]]", "", .)
  
  ## Extracting Start Time & End Time
  df_session$Start_Time <- df$time[df$trial_type == "fullscreen" & !is.na(df$trial_type)][1]
  df_session$End_Time <- df$time[df$trial_type == "fullscreen" & !is.na(df$trial_type)][2]
  df_session$Date <- file %>% 
                     regmatches(., regexpr("\\d{4}-\\d{2}-\\d{2}", .))
  
  ## Extracting Condition Information
  if (any(df_session_orig$condition[which(!is.na(df_session_orig$condition))] == "Forecast")) {
    df_session$Condition <- 'Forecast'    
  }
  if (any(df_session_orig$condition[which(!is.na(df_session_orig$condition))] == "Experience")) {
    df_session$Condition <- 'Experience'    
  }
  
  ## Checking Event Failures
  if (any(df_session_orig$success[!is.na(df_session_orig$success)] == 'false')) {
    warning(paste("At least one event of file ", file, " has recorded an initialization failure. 
                  Please review this file before continuing."))
    df_session$Failures[1] = TRUE
  }
  if (all(df_session_orig$success[!is.na(df_session_orig$success)] == 'true')) {
    df_session$Failures[1] = FALSE    
  }
  
  ## Checking Screen Width
  if (all(df_session_orig$width[which(!is.na(df_session_orig$width))] != df_session_orig$width[which(!is.na(df_session_orig$width))[1]])) {
    warning(paste("At least one event of file ", file, " has recorded a screen width which differs from the others (", df_session_orig$width[which(!is.na(df_session_orig$width))[1]],") . 
                  Please review this file before continuing."))
    df_session$ScreenWidth[1] = NA
  }
  if (all(df_session_orig$width[which(!is.na(df_session_orig$width))] == df_session_orig$width[which(!is.na(df_session_orig$width))[1]])) {
    df_session$ScreenWidth[1] = df_session_orig$width[which(!is.na(df_session_orig$width))[1]]
  }
  
  ## Checking Screen Height
  if (all(df_session_orig$height[which(!is.na(df_session_orig$height))] != df_session_orig$height[which(!is.na(df_session_orig$height))[1]])) {
    warning(paste("At least one event of file ", file, " has recorded a screen height which differs from the others (", df_session_orig$height[which(!is.na(df_session_orig$height))[1]],") . 
                  Please review this file before continuing."))
    df_session$ScreenHeight[1] = NA
  }
  if (all(df_session_orig$height[which(!is.na(df_session_orig$height))] == df_session_orig$height[which(!is.na(df_session_orig$height))[1]])) {
    df_session$ScreenHeight[1] = df_session_orig$height[which(!is.na(df_session_orig$height))[1]]
  }
  
  ## Checking if webaudio is ever not playing
  if (any(df_session_orig$webaudio[!is.na(df_session_orig$webaudio)] == 'false')) {
    warning(paste("At least one event of file ", file, " has recorded that audio did not initialize. 
                  Please review this file before continuing."))
    df_session$WebAudio[1] = FALSE
  }
  if (all(df_session_orig$webaudio[!is.na(df_session_orig$webaudio)] == 'true')) {
    df_session$WebAudio[1] = TRUE    
  }
  
  ## Checking if mobile is ever recorded
  if (any(df_session_orig$mobile[!is.na(df_session_orig$mobile)] == 'true')) {
    warning(paste("At least one event of file ", file, " has recorded that mobile was used to complete the task. 
                  Please review this file before continuing."))
    df_session$MobileUsed[1] = TRUE
  }
  if (all(df_session_orig$mobile[!is.na(df_session_orig$mobile)] == 'false')) {
    df_session$MobileUsed[1] = FALSE    
  }
  
  ## Checking if fullscreen is ever not used
  if (any(df_session_orig$fullscreen[!is.na(df_session_orig$fullscreen)] == 'false')) {
    warning(paste("At least one event of file ", file, " has recorded that full screen was not used to complete the task. 
                  Please review this file before continuing."))
    df_session$FullScreenUsed[1] = FALSE
  }
  if (all(df_session_orig$fullscreen[!is.na(df_session_orig$fullscreen)] == 'true')) {
    df_session$FullScreenUsed[1] = TRUE
  }

  ## Calculating Average and Standard Deviation of VSync
  df_session$VSync_Rate_Avg <- mean(df_session_orig$vsync_rate, na.rm = T)
  df_session$VSync_Rate_SD <- sd(df_session_orig$vsync_rate, na.rm = T)
  
  ## Copying browser and OS information
  df_session$Browser <- df_session_orig$browser[which(!is.na(df_session_orig$browser))[1]] 
  df_session$Browser_Version <- df_session_orig$browser_version[which(!is.na(df_session_orig$browser_version))[1]] 
  df_session$OS <- df_session_orig$os[which(!is.na(df_session_orig$os))[1]] 
  
  ## If any of the MISC events were captured 
  if (any(str_detect(string = df$task[!is.na(df$task)], pattern = "^Misc"))){
   
    ## Copying other information
    df_session$Horror_Enjoy <- df$response[df$task == "Misc_Horror_Enjoy" & !is.na(df$task)] %>%
      gsub("[^0-9.]", "", .) %>%
      as.numeric()
    
    df_session$Attention_Check <- df$response[df$task == "Misc_Attention_Check" & !is.na(df$task)] %>%
      gsub("[^0-9.]", "", .) %>%
      as.numeric()
    
    df_session$Difficulties <- df$response[df$task == "Misc_Difficulties" & !is.na(df$task)] %>%
      str_match(pattern = '"Q0":"(.*?)"') %>%
      .[2]
    
    df_session$Questions <- df$response[df$task == "Misc_Questions" & !is.na(df$task)] %>%
      str_match(pattern = '"Q0":"(.*?)"') %>%
      .[2]
    if (df$response[df$task == "Misc_Familiar_Any" & !is.na(df$task)] == 1){
      df_session$Familiarity <- "No"
    }
    if (df$response[df$task == "Misc_Familiar_Any" & !is.na(df$task)] != 1){
      df_session$Familiarity <- "Yes"
    }
    if (any(df$task[!is.na(df$task)] == "Misc_Familiar_Specific")){
      df_session$Familiar_specific <- df$response[df$task == "Misc_Familiar_Specific" & !is.na(df$task)] %>%
                                      fromJSON() %>%
                                      as.data.frame() %>%
                                      .[,1] %>%
                                      str_replace_all(pattern = "components/screenshots/",
                                                      replacement = "") %>%
                                      str_replace_all(pattern = "\\.png",
                                                      replacement = "") %>%
                                      paste(., collapse = " ")
                                      
    }
     
  }
  
  # ----- Merging Dataframes -----
  
  ## Merging Dataframes
  df <- cbind(df_trials, df_session)
  
  ## Cleaning space
  rm(df_session, df_trials, cols_session)
  
  # ----- Rearranging Variable Names -----
  
  if (any(names(df) == "ERQ_Supp")){
    if (any(names(df) == "Income")) {
      if (all(df$Choice == "Neither")){
        df <- subset(df,
                     select=c("PID", "Date", "Start_Time", "End_Time", "Condition", "Trial", "Stimulus", "Choice",
                              "IntBefore", "IntAfter", "ERQ_Supp", "ERQ_Reapp",
                              "DERS", "DERS_Nonaccept", "DERS_Goals", "DERS_Impulse", "DERS_Awareness", "DERS_Strategies",
                              "DERS_Clarity", "IUS", "IUS_F1", "IUS_F2", "Horror_Enjoy", "Familiarity", "Familiar_specific",
                              "Age", "Gender_Identity", "Sex", "Race", "Marital_Status", "Edu_Num", "Edu_Cat", "Income", "Failures",
                              "ScreenWidth", "ScreenHeight", "WebAudio", "Browser", "Browser_Version", "MobileUsed",
                              "OS", "FullScreenUsed", "VSync_Rate_Avg", "VSync_Rate_SD",
                              "Attention_Check", "Difficulties", "Questions", "RT_sec_Choice", "RT_sec_IntBefore",
                              "RT_sec_IntAfter", "RT_sec_ERQ", "RT_sec_DERS", "RT_sec_IUS"))
      }
      if (any(df$Choice != "Neither")){
        df <- subset(df,
                     select=c("PID", "Date", "Start_Time", "End_Time", "Condition", "Trial", "Stimulus", "Choice",
                              "IntBefore", "IntAfter", "IntReduce", "Effort", "Success", "ERQ_Supp", "ERQ_Reapp",
                              "DERS", "DERS_Nonaccept", "DERS_Goals", "DERS_Impulse", "DERS_Awareness", "DERS_Strategies",
                              "DERS_Clarity", "IUS", "IUS_F1", "IUS_F2", "Horror_Enjoy", "Familiarity", "Familiar_specific",
                              "Age", "Gender_Identity", "Sex", "Race", "Marital_Status", "Edu_Num", "Edu_Cat", "Income", "Failures",
                              "ScreenWidth", "ScreenHeight", "WebAudio", "Browser", "Browser_Version", "MobileUsed",
                              "OS", "FullScreenUsed", "VSync_Rate_Avg", "VSync_Rate_SD",
                              "Attention_Check", "Difficulties", "Questions", "RT_sec_Choice", "RT_sec_IntBefore",
                              "RT_sec_IntAfter", "RT_sec_IntReduce", "RT_sec_Effort",
                              "RT_sec_Success", "RT_sec_ERQ", "RT_sec_DERS", "RT_sec_IUS"))
      }
    }
    
    if (all(names(df) != "Income")) {
      if (all(df$Choice == "Neither")){
        df <- subset(df,
                     select = c("PID", "Date", "Start_Time", "End_Time", "Condition", "Trial", "Stimulus", "Choice",
                                "IntBefore", "IntAfter", "ERQ_Supp", "ERQ_Reapp",
                                "DERS", "DERS_Nonaccept", "DERS_Goals", "DERS_Impulse", "DERS_Awareness", "DERS_Strategies",
                                "DERS_Clarity", "IUS", "IUS_F1", "IUS_F2", "Horror_Enjoy", "Familiarity", "Familiar_specific",
                                "Age", "Gender_Identity", "Sex", "Race", "Marital_Status", "Edu_Num", "Edu_Cat", "Failures",
                                "ScreenWidth", "ScreenHeight", "WebAudio", "Browser", "Browser_Version", "MobileUsed",
                                "OS", "FullScreenUsed", "VSync_Rate_Avg", "VSync_Rate_SD",
                                "Attention_Check", "Difficulties", "Questions", "RT_sec_Choice", "RT_sec_IntBefore",
                                "RT_sec_IntAfter", "RT_sec_ERQ", "RT_sec_DERS", "RT_sec_IUS"))
      }
      if (any(df$Choice != "Neither")){
        df <- subset(df,
                     select = c("PID", "Date", "Start_Time", "End_Time", "Condition", "Trial", "Stimulus", "Choice",
                                "IntBefore", "IntAfter", "IntReduce", "Effort", "Success", "ERQ_Supp", "ERQ_Reapp",
                                "DERS", "DERS_Nonaccept", "DERS_Goals", "DERS_Impulse", "DERS_Awareness", "DERS_Strategies",
                                "DERS_Clarity", "IUS", "IUS_F1", "IUS_F2", "Horror_Enjoy", "Familiarity", "Familiar_specific",
                                "Age", "Gender_Identity", "Sex", "Race", "Marital_Status", "Edu_Num", "Edu_Cat", "Failures",
                                "ScreenWidth", "ScreenHeight", "WebAudio", "Browser", "Browser_Version", "MobileUsed",
                                "OS", "FullScreenUsed", "VSync_Rate_Avg", "VSync_Rate_SD",
                                "Attention_Check", "Difficulties", "Questions", "RT_sec_Choice", "RT_sec_IntBefore",
                                "RT_sec_IntAfter", "RT_sec_IntReduce", "RT_sec_Effort",
                                "RT_sec_Success", "RT_sec_ERQ", "RT_sec_DERS", "RT_sec_IUS"))
      }
    }
  }

  if (all(names(df) != "ERQ_Supp")){
    if (any(names(df) == "Income")) {
      if (all(df$Choice == "Neither")){
        df <- subset(df,
                     select=c("PID", "Date", "Start_Time", "End_Time", "Condition", "Trial", "Stimulus", "Choice",
                              "IntBefore", "IntAfter", "Failures",
                              "ScreenWidth", "ScreenHeight", "WebAudio", "Browser", "Browser_Version", "MobileUsed",
                              "OS", "FullScreenUsed", "VSync_Rate_Avg", "VSync_Rate_SD",
                              "RT_sec_Choice", "RT_sec_IntBefore",
                              "RT_sec_IntAfter"))
      }
      if (any(df$Choice != "Neither")){
        df <- subset(df,
                     select=c("PID", "Date", "Start_Time", "End_Time", "Condition", "Trial", "Stimulus", "Choice",
                              "IntBefore", "IntAfter", "IntReduce", "Effort", "Success", "Failures",
                              "ScreenWidth", "ScreenHeight", "WebAudio", "Browser", "Browser_Version", "MobileUsed",
                              "OS", "FullScreenUsed", "VSync_Rate_Avg", "VSync_Rate_SD",
                              "RT_sec_Choice", "RT_sec_IntBefore",
                              "RT_sec_IntAfter", "RT_sec_IntReduce", "RT_sec_Effort",
                              "RT_sec_Success"))
      }
    }
    
    if (all(names(df) != "Income")) {
      if (all(df$Choice == "Neither")){
        df <- subset(df,
                     select = c("PID", "Date", "Start_Time", "End_Time", "Condition", "Trial", "Stimulus", "Choice",
                                "IntBefore", "IntAfter", "Failures",
                                "ScreenWidth", "ScreenHeight", "WebAudio", "Browser", "Browser_Version", "MobileUsed",
                                "OS", "FullScreenUsed", "VSync_Rate_Avg", "VSync_Rate_SD",
                                "RT_sec_Choice", "RT_sec_IntBefore",
                                "RT_sec_IntAfter"))
      }
      if (any(df$Choice != "Neither")){
        df <- subset(df,
                     select = c("PID", "Date", "Start_Time", "End_Time", "Condition", "Trial", "Stimulus", "Choice",
                                "IntBefore", "IntAfter", "IntReduce", "Effort", "Success", "Failures",
                                "ScreenWidth", "ScreenHeight", "WebAudio", "Browser", "Browser_Version", "MobileUsed",
                                "OS", "FullScreenUsed", "VSync_Rate_Avg", "VSync_Rate_SD",
                                "RT_sec_Choice", "RT_sec_IntBefore",
                                "RT_sec_IntAfter", "RT_sec_IntReduce", "RT_sec_Effort",
                                "RT_sec_Success"))
      }
    }
  }
  
  
  
  # ----- Output -----
  return(df)
  
}
